name: "Increment Version on Push"

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: "Increment version"
        run: node portfolio/scripts/version.js

      - name: "Commit and push changes"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Bump version"
          branch: main
          file_pattern: "portfolio/package.json"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions <actions@github.com>"
